# Generated by Django 3.2.10 on 2022-01-05 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('id',)},
        ),
    ]
